name: krispr_test
channels:
  - bioconda
  - defaults
  - conda-forge
dependencies:
  - biopython=1.85
  - blas=1.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - cd-hit=4.8.1
  - joblib=1.4.2
  - libcxx=19.1.7
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libopenblas=0.3.21
  - libsqlite=3.49.1
  - libzlib=1.3.1
  - llvm-openmp=19.1.7
  - ncurses=6.5
  - numexpr=2.10.1
  - numpy=2.2.2
  - numpy-base=2.2.2
  - openssl=3.4.1
  - pandas=2.2.3
  - pip=25.0
  - python=3.13.2
  - python-dateutil=2.9.0post0
  - python-tzdata=2023.3
  - python_abi=3.13
  - pytz=2024.1
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.1
  - setuptools=72.1.0
  - six=1.16.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tzdata=2025a
  - wheel=0.45.1
