name: krispr
channels:
  - bioconda
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - biopython=1.85
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - cd-hit=4.8.1
  - joblib=1.4.2
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libexpat=2.6.4
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblapack=3.9.0
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libopenblas=0.3.29
  - libsqlite=3.49.1
  - libstdcxx=14.2.0
  - libuuid=2.38.1
  - libzlib=1.3.1
  - ncurses=6.5
  - numpy=2.2.3
  - openssl=3.4.1
  - pandas=2.2.3
  - pip=25.0.1
  - python=3.13.2
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.13
  - pytz=2024.1
  - readline=8.2
  - scikit-learn=1.6.1
  - scipy=1.15.2
  - setuptools=75.8.0
  - six=1.17.0
  - threadpoolctl=3.5.0
  - tk=8.6.13
  - tzdata=2025a
